### PR TITLE
[BUGFIX] #24: exception when user name and/or password is incorrect in Frontend

### PR DESCRIPTION
**Pull request by dmitryd**
Fixes the issue by checking that variable is set to a proper object.

### CODE REVIEW

**Comment by liayn** [comment]
Since version 8 the TimeTracker is a singleton, so we should adjust this to use `makeInstance` if the global `TT` is not set

**Comment by dmitryd** [comment]
Why should we create TT if it does not exist? If it does not exist, it means nobody is logging anything. Not worth creating it than.

**Comment by liayn** [comment]
The `TT` is not set at all anymore since v8. Checking the global only means that this logging will only happen in v7.
Therefore I would create the TimeTracker.

But I have no hard feelings about this, we can also simply remove the TT stuff completely.

**Comment by dmitryd** [comment]
I would prefer to remove it. I am not sure if I added it and if I did, why. May be, it was when the ext was originally programmed for 4.x, and TYPO3 did not have any other logging ways.

It could make sense to use a regular logger these days but than EXT:openid will show false warnings in logs every time when password was entered incorrectly. So the best would be to remove it. I will update the PR.

**Comment by dmitryd** [comment]
To the maintainer: please, squash when merging. Thanks!

**Pull request merged**
