### PR TITLE
[BUGFIX] Correct normalization of openid url

### PR DESCRIPTION
**Pull request by dalder**
Since the normalization of the openid is not working correctly, an openid
without a protocol and without a user in the database will never do a
request to the openid server.

So we use the normalization of the openid library build in. Then the
normalization is done right.

Resolves: #7
Related: #6
Releases: master

### CODE REVIEW

**Comment by dalder** [comment]
sorry, my bad, done

**Comment by liayn** [comment]
What happened to the commit message now?

**Comment by dalder** [comment]
Hi, do you need something else? Is something unclear which is keeping you from merging the request?

**Comment by liayn** [comment]
I didn't get a notification that you updated the commits.
Why do we have two commits here now? Please squash them into a single one.

**Comment by liayn** [comment]
Ping?

**Comment by liayn** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
