### PR TITLE
Show user settings in TYPO3 v. 10.4.2

### PR DESCRIPTION
**Pull request by escapevisual**
Update deprecated function calls to edit user settings.

### CODE REVIEW

**Review by cabi — APPROVED** [review]
Tested successful in TYPO3 10.4.3

**Comment by djcprinse** [comment]
I can confirm this patch works. Tested it with our projects running TYPO3 versions 8.7.34, 9.5.18 and 10.4.4.

**Comment by djcprinse** [comment]
Unfortunately I came across some problem with missing use statements. Because I lack the rights to adjust these use statements in this PR, I've opened #36 to fix these issues.

**Comment by bmack** [comment]
Solved already

**Pull request closed without merging**
